### ISSUE TITLE
ECONNRESET

### ISSUE THREAD

**Issue by tofutim** [substack/node-smtp-protocol#48]
Sometimes I hit a bad server and I get

events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: read ECONNRESET
    at exports._errnoException (util.js:837:11)
    at TCP.onread (net.js:544:26)

**Comment by tofutim** [comment]
Is it because I try to do more than 1 connection at a time? Can I only do only one smtp at a time?

**Comment by tofutim** [comment]
One of the mail servers was bad - need to find a way to catch that error.

**Comment by tofutim** [comment]
Another one I got was 

events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: connect ECONNREFUSED
    at exports._errnoException (util.js:746:11)
    at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1000:19)

Need a way of catching that error and associating it with the server - so a general error handler would not work.

**Comment by tofutim** [comment]
Aha, figured it out - I needed to get the stream and use

.on('error', function (error) {
    console.dir(error);
  })
