### ISSUE TITLE
how do I catch systax error parsing?

### ISSUE THREAD

**Issue by tofutim** [substack/node-smtp-protocol#49]
events.js:141
      throw er; // Unhandled 'error' event
      ^

Error: syntax error parsing: 554 
    at /Users/tim/node_modules/smtp-protocol/lib/server/parser.js:29:16
    at Socket.ondata (/Users/tim/node_modules/smtp-protocol/lib/parse_data.js:25:21)
    at emitOne (events.js:77:13)
    at Socket.emit (events.js:169:7)
    at readableAddChunk (_stream_readable.js:146:16)
    at Socket.Readable.push (_stream_readable.js:110:10)
    at TCP.onread (net.js:523:20)

**Comment by tofutim** [comment]
Also how do I set the timeout from

  var stream = smtp.connect(mx, 25, options={}, function(client) {

**Comment by tofutim** [comment]
Looks like it comes from here

ServerParser.prototype.parseLines = function (cb) {
    var self = this;
    var continuation = null;
    
    self.parseData(function (line) {
        var m = line.match(/^(\d+)(?:([- ])(.+))?$/);
        var code = m && parseInt(m[1], 10);
        
        if (!m) {
            cb(new Error('syntax error parsing: ' + line));
        }

Although I am just using the client, so not sure why it is looking at server /parser.js
